CREATE TABLE [dbo].[BicycleLine]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[CityID] INT NOT NULL DEFAULT 1,
    [Start] NVARCHAR(150) NOT NULL, 
    [End] NVARCHAR(150) NOT NULL, 
	[StartLat]  FLOAT NOT NULL DEFAULT 0, 
	[StartLng]  FLOAT NOT NULL DEFAULT 0, 
	[EndLat]  FLOAT NOT NULL DEFAULT 0, 
	[EndLng]  FLOAT NOT NULL DEFAULT 0, 
	[Quantity] INT NOT NULL,
	CONSTRAINT [PK_BicycleLine] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_BicycleLine_City] FOREIGN KEY ([CityID]) REFERENCES [dbo].[City] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
