CREATE TABLE [dbo].[Building]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[CityID] INT NOT NULL, 
    [Address] NVARCHAR(150) NOT NULL, 
	[Lat] FLOAT NOT NULL DEFAULT(0), 
	[Lng] FLOAT NOT NULL DEFAULT(0), 
	[Capacity] INT, 
	CONSTRAINT [PK_Building] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_Building_City] FOREIGN KEY ([CityID]) REFERENCES [dbo].[City] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
