CREATE TABLE [dbo].[Bus]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
    [TransporteurID] INT NOT NULL, 
    [RouteID] INT NOT NULL, 
    [BrandID] INT NOT NULL, 
    [Number] NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_Bus] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_Bus_Transporteur] FOREIGN KEY ([TransporteurID]) REFERENCES [dbo].[Transporteur] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [FK_Bus_Route] FOREIGN KEY ([RouteID]) REFERENCES [dbo].[Route] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [FK_Bus_Brand] FOREIGN KEY ([BrandID]) REFERENCES [dbo].[Brand] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
