CREATE TABLE [dbo].[BusPhoto]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
    [BusID] INT NOT NULL, 
    [ImagePath] NVARCHAR(150) NOT NULL,
	CONSTRAINT [PK_BusPhoto] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_BusPhoto_Bus] FOREIGN KEY ([BusID]) REFERENCES [dbo].[Bus] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
