CREATE TABLE [dbo].[BycicleDirection]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[UserID] INT NOT NULL,
	[Waypoints] VARCHAR(MAX) NOT NULL,
	[PolyLine] VARCHAR(MAX) NOT NULL,
	[Processed] BIT NOT NULL,
	[AddedDate] DATETIME NOT NULL,
	CONSTRAINT [PK_BycicleDirection] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_BycicleDirection_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
