CREATE TABLE [dbo].[BycicleDirection]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[CityID] INT NOT NULL DEFAULT 1,
	[UserID] INT NOT NULL,
	[Waypoints] VARCHAR(MAX) NOT NULL,
	[PolyLine] VARCHAR(MAX) NOT NULL,
	[Length] FLOAT NOT NULL DEFAULT 0,
	[Processed] BIT NOT NULL,
	[AddedDate] DATETIME NOT NULL,
	CONSTRAINT [PK_BycicleDirection] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_BycicleDirection_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [FK_BicycleDirection_City] FOREIGN KEY ([CityID]) REFERENCES [dbo].[City] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
