CREATE TABLE [dbo].[Comment]
(
	[ID] INT IDENTITY (1, 1) NOT NULL, 
	[UserID] INT NOT NULL,
	[ParentID] INT NULL,
	[AddedDate] DATETIME NOT NULL, 
	[Text] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_Comment_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_Comment_Comment] FOREIGN KEY ([ParentID]) REFERENCES [dbo].[Comment] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
)
