CREATE TABLE [dbo].[Goal]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[UserID] INT NOT NULL, 
    [IsPublic] BIT NOT NULL,
	[Url] NVARCHAR(140) NOT NULL,
	[Text] NVARCHAR(140) NOT NULL,
	[Count] INT NOT NULL,
	[Progress] INT NOT NULL,
	[AddedDate] DATETIME NOT NULL,
	[IsReady] BIT NOT NULL,
    [ColumnsCount] INT NOT NULL, 
    CONSTRAINT [PK_Goal] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_Goal_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
