CREATE TABLE [dbo].[GoalCell]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[GoalID] INT NOT NULL, 
	[Number] INT NOT NULL,
	[State] INT NOT NULL,
	[AddedDate] DATETIME NULL,
    CONSTRAINT [PK_GoalCell] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_GoalCell_Goal] FOREIGN KEY ([GoalID]) REFERENCES [dbo].[Goal] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
