CREATE TABLE [dbo].[InstagramPhoto]
(
	[ID] INT IDENTITY (1, 1) NOT NULL,
	[GlobalId] NVARCHAR(500) NOT NULL,
	[CityID] INT NOT NULL,
	[Lat] FLOAT (53)    NOT NULL,
	[Lng] FLOAT (53)    NOT NULL,
	[CreatedTime] DATETIME NOT NULL, 
	[PhotoUrl] NVARCHAR(200) NOT NULL,
	[Caption] NVARCHAR(MAX) NULL,
	[Tags] NVARCHAR(MAX) NULL,
	[UserGlobalId] BIGINT NOT NULL,
	[UserName] NVARCHAR(200) NOT NULL,
	[UserFullName] NVARCHAR(200) NOT NULL,
	[AddedDate] DATETIME NOT NULL,
	CONSTRAINT [PK_InstagramPhoto] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_InstagramPhoto_City] FOREIGN KEY ([CityID]) REFERENCES [dbo].[City] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
)
