CREATE TABLE [dbo].[Place]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
	[Name]	NVARCHAR(50) NOT NULL,
	[Lat]	FLOAT	NOT NULL,
	[Lng]	FLOAT	NOT NULL,
	[Distance]	INT	NOT NULL,
	[Zoom]	INT	NOT NULL,
	[MinDate]	DATETIME	NOT NULL,
	[MaxDate]	DATETIME	NOT NULL,
	CONSTRAINT [PK_Place] PRIMARY KEY CLUSTERED ([ID] ASC),
)
