CREATE TABLE [dbo].[RuleReport]
(
	[ID]  INT IDENTITY (1, 1) NOT NULL,
    [RuleID] INT NOT NULL, 
    [ReportID] INT NOT NULL,
	CONSTRAINT [PK_RuleReport] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_RuleReport_Rule] FOREIGN KEY ([RuleID]) REFERENCES [dbo].[Rule] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [FK_RuleReport_Report] FOREIGN KEY ([ReportID]) REFERENCES [dbo].[Report] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
)
