CREATE TABLE [dbo].[Shop]
(
	[Id] INT NOT NULL IDENTITY (1, 1),
	[UserID] INT NOT NULL,
    [Position] NVARCHAR(50) NULL,
	CONSTRAINT [PK_Shop] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Shop_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
