CREATE TABLE [dbo].[Visualization]
(
	[ID] INT IDENTITY (1, 1) NOT NULL, 
	[ShareLink] NVARCHAR(10) NOT NULL DEFAULT '',
	[UserID] INT NOT NULL,
	[Name] NVARCHAR(300),
	[AddedDate] DATETIME NOT NULL, 
	CONSTRAINT [PK_Visualization] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_Visualization_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
)
